version: 1.4.{build}-dev
branches:
  only:
  - release
configuration: Release
init:
- git config --global core.autocrlf true
before_build:
- nuget restore
build:
  publish_nuget: true
  verbosity: minimal